apiVersion: networking.k8s.io/v1
   
kind: Ingress
   
metadata:
   
  name: example-ingress
   
spec:
   
  rules:
   
    - host: localhost
   
      http:
   
        paths:
   
          - path: /
   
            pathType: Prefix
   
            backend:
   
              service:
   
                name: load-balancer
   
                port:
   
                  number: 8080
